name: AntiSwearFilter
version: '1.0-SNAPSHOT'
main: hu.shiya.antiSwearFilter.AntiSwearFilter
api-version: '1.21'
authors: [ Shiya ]
description: A Plugin that filters the chat from bad words.
permissions:
  #chat-pass:
   # default: false
    #description: Pass the auto-server mute system.
  moderator:
    default: false
    description: Able to see what people swear.